/// Flutter icons IconsOwn
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsOwn
///      fonts:
///       - asset: fonts/IconsOwn.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconsOwn {
  IconsOwn._();

  static const _kFontFam = 'IconsOwn';
  static const String? _kFontPkg = null;

  static const IconData person = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ordersavedpass = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addcircle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop_alt = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_downward = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_forward = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_upward = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ordersave = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_empty = IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
